@startuml
'https://plantuml.com/class-diagram

class RaftGroupService
class NodeOptions

class PartitionListener {
  Map<Integer, PartitionListener> tablePartitionListeners

  PendingComparableValuesTracker<HybridTimestamp, Void> safeTime
  Map<StorageType, PendingComparableValuesTracker<Long, Void>> storageIndexTracker
}

class TablePartitionListener {
  PartitionDataStorage partitionDataStorage
  TxStateStorage txStateStorage

  StorageUpdateHandler storageUpdateHandler
}

class SnapshotAwarePartitionDataStorage {
  MvPartitionStorage partitionStorage
  PartitionsSnapshots partitionsSnapshots
}

interface MvPartitionStorage
interface PartitionsSnapshots
interface TxStateStorage

RaftGroupService o-- NodeOptions
NodeOptions o-- PartitionListener
PartitionListener o-- TablePartitionListener
TablePartitionListener o-- SnapshotAwarePartitionDataStorage
TablePartitionListener o-- "one" TxStateStorage

SnapshotAwarePartitionDataStorage o-- "one" MvPartitionStorage
SnapshotAwarePartitionDataStorage o-- PartitionsSnapshots
@enduml
